// <auto-generated />
using System;
using FormUp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormUp.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240112170619_AddWorkoutBackingFieldToActivity")]
    partial class AddWorkoutBackingFieldToActivity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormUp.Api.Common.Persistence.GeolocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Geolocations");
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Exercises.ExerciseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("acc3fe8d-c7c9-4bc4-88b9-6736ca4b26a0"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(390),
                            Description = "exercises.squat.description",
                            ImageURL = "https://legionathletics.com/wp-content/uploads/2019/05/arnold-squat.jpg",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(390),
                            Name = "exercises.squat.name",
                            NormalizedName = "exercises.squat.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("813629e9-2ae8-4617-822e-5925bb098ccc"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(400),
                            Description = "exercises.dead-lift.description",
                            ImageURL = "https://miro.medium.com/v2/resize:fit:1024/0*UkQCo1eLsXjoXn4v.jpg",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(400),
                            Name = "exercises.dead-lift.name",
                            NormalizedName = "exercises.dead-lift.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("e56414dc-ef26-4f41-a5be-0be894a262d4"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(400),
                            Description = "exercises.shoulder-press.description",
                            ImageURL = "https://legionathletics.com/wp-content/uploads/2023/10/Dumbbell-Shoulder-Press-before-after.png",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(400),
                            Name = "exercises.shoulder-press.name",
                            NormalizedName = "exercises.shoulder-press.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("4ee2eeef-0cda-485b-9723-c45b90296130"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(410),
                            Description = "exercises.pull-up.description",
                            ImageURL = "https://hips.hearstapps.com/hmg-prod/images/mh0418-fit-pul-01-1558551798.jpg?crop=0.749xw:1.00xh;0.251xw,0&resize=1200:*",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(410),
                            Name = "exercises.pull-up.name",
                            NormalizedName = "exercises.pull-up.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("494b12a8-3cdf-4db0-98bf-85e0cca8d3a4"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(410),
                            Description = "exercises.dip.description",
                            ImageURL = "https://www.muscleandfitness.com/wp-content/uploads/2018/07/1109-dip.jpg?w=800&quality=86&strip=all",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(410),
                            Name = "exercises.dip.name",
                            NormalizedName = "exercises.dip.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("2239df6e-9146-410d-927a-a2368ad82188"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(410),
                            Description = "exercises.bench-press.description",
                            ImageURL = "https://caliberstrong.com/wp-content/uploads/2020/04/how-to-bench-press.jpg",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(410),
                            Name = "exercises.bench-press.name",
                            NormalizedName = "exercises.bench-press.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("42f77d86-1cfe-4f56-a9e7-744874c43dd4"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(420),
                            Description = "exercises.lunge.description",
                            ImageURL = "https://hortonbarbell.com/wp-content/uploads/2022/05/Dumbbell-Lunge.png",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(420),
                            Name = "exercises.lunge.name",
                            NormalizedName = "exercises.lunge.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("a11e442c-8d45-4002-9120-20db156fe687"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(420),
                            Description = "exercises.push-up.description",
                            ImageURL = "https://www.fitnesseducation.edu.au/wp-content/uploads/2017/03/Pushups.jpg",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(420),
                            Name = "exercises.push-up.name",
                            NormalizedName = "exercises.push-up.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("b9d4beb6-a758-4d8c-9448-dd8cd76d719b"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(420),
                            Description = "exercises.curl.description",
                            ImageURL = "https://hortonbarbell.com/wp-content/uploads/2023/01/How-To-Do-Tempo-Bicep-Curls.png",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(420),
                            Name = "exercises.curl.name",
                            NormalizedName = "exercises.curl.normalized-name"
                        });
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Gyms.GymEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gyms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("111efe1a-6e8f-4b03-8a1b-1d8d05f6ec5f"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(820),
                            Latitude = 49.178859520009325,
                            Longitude = 16.59588166754828,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(820),
                            Name = "Posilovna Velký Průvan"
                        },
                        new
                        {
                            Id = new Guid("36963396-cc12-407f-91a1-212f22ba6775"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(830),
                            Latitude = 49.179083949535297,
                            Longitude = 16.596503940037902,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(830),
                            Name = "Posilovna Malý Průvan"
                        },
                        new
                        {
                            Id = new Guid("d92482c1-8d06-4c28-addf-c6485509290f"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(830),
                            Latitude = 49.177089060496634,
                            Longitude = 16.606190093594201,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(830),
                            Name = "AZ Fitness"
                        },
                        new
                        {
                            Id = new Guid("851c1882-85b8-4259-bf1c-545db2487509"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(840),
                            Latitude = 49.181262112264804,
                            Longitude = 16.60282245697524,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(840),
                            Name = "NewPark Gym"
                        },
                        new
                        {
                            Id = new Guid("b1f7c1c6-551f-4169-831b-92eb13da57d1"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(840),
                            Latitude = 49.180330210607991,
                            Longitude = 16.606384581697789,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(840),
                            Name = "Energy Fitness Club"
                        },
                        new
                        {
                            Id = new Guid("e8d0ab41-04e5-49e1-8595-2128b155efeb"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(840),
                            Latitude = 49.215051402565855,
                            Longitude = 16.609402145470618,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(840),
                            Name = "Hulk Gym"
                        },
                        new
                        {
                            Id = new Guid("21258a74-9d4d-4763-98e6-ad4c0e23739a"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(850),
                            Latitude = 49.212976899683049,
                            Longitude = 16.609015907373617,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(850),
                            Name = "Fitness Boby"
                        },
                        new
                        {
                            Id = new Guid("d2977ca2-4d25-4b50-919e-24d7cd716f5d"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(850),
                            Latitude = 49.218555432690493,
                            Longitude = 16.624250854578833,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(850),
                            Name = "Blackfield Gym"
                        },
                        new
                        {
                            Id = new Guid("1b2a5d3b-a9a3-4947-addb-717a89ad29de"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(850),
                            Latitude = 49.190492694739753,
                            Longitude = 16.617386769256324,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(850),
                            Name = "Form Factory Fitness Club Vlněna"
                        },
                        new
                        {
                            Id = new Guid("fcc11923-4c76-4461-8184-0ab58c642568"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(860),
                            Latitude = 49.208489226784764,
                            Longitude = 16.605422062883459,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(860),
                            Name = "Form Factory Fitness Club Lužánky"
                        });
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Translations.TranslationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Locale", "Key");

                    b.ToTable("Translations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66584d17-300a-4dac-9015-e39f5360c1f4"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(530),
                            Key = "exercises.squat.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(530),
                            Value = "Squat"
                        },
                        new
                        {
                            Id = new Guid("badd68f9-9cf5-45af-b27b-a629e862fb43"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(540),
                            Key = "exercises.squat.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(540),
                            Value = "Dřep"
                        },
                        new
                        {
                            Id = new Guid("1dc335f7-5a0f-4b2f-a51d-983c471fe76f"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(540),
                            Key = "exercises.squat.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(540),
                            Value = "SQUAT"
                        },
                        new
                        {
                            Id = new Guid("19186a5c-6dcc-4df6-b31c-220fa1bc2564"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(540),
                            Key = "exercises.squat.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(540),
                            Value = "DREP"
                        },
                        new
                        {
                            Id = new Guid("e11cb572-65d3-4c87-ac51-a62b32cd16bb"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(550),
                            Key = "exercises.squat.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(550),
                            Value = "A fundamental lower body exercise targeting the legs, hamstrings, and glutes. Stand with feet shoulder-width apart, lower your body by bending your knees, and return to the starting position."
                        },
                        new
                        {
                            Id = new Guid("4f234712-5172-41a7-a2fd-56bbceb72b18"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(550),
                            Key = "exercises.squat.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(550),
                            Value = "Dřep posiluje dolní část těla, především nohy, hamstrings a hýždě. Vykonává se stáním s váhou na ramenou a poklesem do pravého úhlu v kolenou."
                        },
                        new
                        {
                            Id = new Guid("2918047d-b1ab-4052-9e76-b8b26c5180ee"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(550),
                            Key = "exercises.dead-lift.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(550),
                            Value = "Dead-lift"
                        },
                        new
                        {
                            Id = new Guid("01d9a2f7-c424-4739-88eb-57e61cae7d7c"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(560),
                            Key = "exercises.dead-lift.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(560),
                            Value = "Mrtvý tah"
                        },
                        new
                        {
                            Id = new Guid("99beba73-88b6-47cb-91ab-ec220308adb3"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(570),
                            Key = "exercises.dead-lift.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(570),
                            Value = "DEADLIFT"
                        },
                        new
                        {
                            Id = new Guid("49ea0ee3-30ea-4f26-8e96-a07bfcbf3c2f"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(570),
                            Key = "exercises.dead-lift.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(570),
                            Value = "MRTVYTAH"
                        },
                        new
                        {
                            Id = new Guid("8cbdf6a7-5e8b-43bf-a2fa-ea9a1edba144"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(570),
                            Key = "exercises.dead-lift.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(570),
                            Value = "A compound exercise for overall strength, focusing on the back, glutes, hamstrings, and lower back. Start with the weight on the ground, hinge at the hips, lift the weight by straightening your hips and knees."
                        },
                        new
                        {
                            Id = new Guid("0300b9f3-ea58-4a0d-a8f0-7a769919a5ed"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(580),
                            Key = "exercises.dead-lift.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(580),
                            Value = "Mrtvý tah je cvik na posílení zad, hýždí a hamstringů, provedený ohnutím v pase a zdvihem váhy z podlahy s udržením rovné páteře."
                        },
                        new
                        {
                            Id = new Guid("fb87cd90-294f-4460-892a-23749429d02f"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(580),
                            Key = "exercises.shoulder-press.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(580),
                            Value = "Shoulder press"
                        },
                        new
                        {
                            Id = new Guid("92e5d0b2-832d-4ee5-bf0b-8019890e6e06"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(580),
                            Key = "exercises.shoulder-press.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(580),
                            Value = "Tlak na ramena"
                        },
                        new
                        {
                            Id = new Guid("27ca5a63-2eab-4954-86c3-f4f8d5fac004"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(590),
                            Key = "exercises.shoulder-press.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(590),
                            Value = "SHOULDERPRESS"
                        },
                        new
                        {
                            Id = new Guid("78e3701b-5513-4895-9db7-da92b97f481f"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(590),
                            Key = "exercises.shoulder-press.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(590),
                            Value = "TLAKNARAMENA"
                        },
                        new
                        {
                            Id = new Guid("cce34cb2-52fb-408e-b95f-e3017a7938fc"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(600),
                            Key = "exercises.shoulder-press.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(600),
                            Value = "An upper body exercise concentrating on shoulder muscles. Whether sitting or standing, press weights or other resistance overhead, emphasizing controlled movements."
                        },
                        new
                        {
                            Id = new Guid("28f18054-609d-40b3-af46-3b9da83f21f3"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(600),
                            Key = "exercises.shoulder-press.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(600),
                            Value = "Tlaky na ramena zaměřují se na posílení ramenních svalů a vykonávají se tlačením činek nad hlavu."
                        },
                        new
                        {
                            Id = new Guid("fa692408-d6f3-4560-a9dd-b17c30d975b0"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(600),
                            Key = "exercises.pull-up.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(600),
                            Value = "Pull up"
                        },
                        new
                        {
                            Id = new Guid("7a07d80e-9823-4b68-8522-24b6d2cf8596"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(610),
                            Key = "exercises.pull-up.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(610),
                            Value = "Shyb"
                        },
                        new
                        {
                            Id = new Guid("09a3ab29-75d0-4930-89f7-13e7c1f1e1ec"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(610),
                            Key = "exercises.pull-up.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(610),
                            Value = "PULLUP"
                        },
                        new
                        {
                            Id = new Guid("7adefe10-d4ae-4603-9870-f82152156445"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(610),
                            Key = "exercises.pull-up.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(610),
                            Value = "SHYB"
                        },
                        new
                        {
                            Id = new Guid("050a56c9-44a1-4072-a53d-eeaa803c68ce"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(620),
                            Key = "exercises.pull-up.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(620),
                            Value = "An effective upper body exercise primarily targeting the back and biceps. Hang from a bar with palms facing away, pull your body up until your chin passes the bar, and lower back down."
                        },
                        new
                        {
                            Id = new Guid("90e75daf-787b-49d5-8337-6f21e117660f"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(620),
                            Key = "exercises.pull-up.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(620),
                            Value = "Shyb je izolovaný cvik pro tricepsy, provádí se zvedáním váhy pomocí prodloužení paže."
                        },
                        new
                        {
                            Id = new Guid("7e8f13a3-7bc5-47c3-8035-127f469d3fb3"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(630),
                            Key = "exercises.dip.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(630),
                            Value = "Dip"
                        },
                        new
                        {
                            Id = new Guid("c603e24a-9e7d-40ab-8b56-753fcc8a78c7"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(630),
                            Key = "exercises.dip.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(630),
                            Value = "Klik na bradlech"
                        },
                        new
                        {
                            Id = new Guid("8342aaea-6262-4c56-bf27-5e75aed0f6e7"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(630),
                            Key = "exercises.dip.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(630),
                            Value = "DIP"
                        },
                        new
                        {
                            Id = new Guid("78b56ab6-8490-4940-8b4d-e2e16d505c40"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(640),
                            Key = "exercises.dip.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(640),
                            Value = "KLIKNABRADLECH"
                        },
                        new
                        {
                            Id = new Guid("632f3e5a-f037-43fa-8639-4d83048aec88"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(640),
                            Key = "exercises.dip.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(640),
                            Value = "An isolation exercise for the triceps and chest. Support yourself on parallel bars, lower your body by bending your elbows, and push back up."
                        },
                        new
                        {
                            Id = new Guid("ed9449da-626a-4710-bc68-8a5e94902ff8"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(640),
                            Key = "exercises.dip.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(640),
                            Value = "Kliky na bradlech posilují horní část těla, zejména hrudník, tricepsy a deltové svaly."
                        },
                        new
                        {
                            Id = new Guid("1fb4a00a-2ce0-4f23-a162-4382d370ddfb"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(650),
                            Key = "exercises.bench-press.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(650),
                            Value = "Bench press"
                        },
                        new
                        {
                            Id = new Guid("be56bbc7-2228-40dc-a158-e635fffdda82"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(650),
                            Key = "exercises.bench-press.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(650),
                            Value = "Bench press"
                        },
                        new
                        {
                            Id = new Guid("d31dfa2e-edd7-429a-8f27-45722fed1cca"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(660),
                            Key = "exercises.bench-press.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(660),
                            Value = "BENCHPRESS"
                        },
                        new
                        {
                            Id = new Guid("4d7d70cc-6847-436c-9141-d7725af2dd7d"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(660),
                            Key = "exercises.bench-press.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(660),
                            Value = "BENCHPRESS"
                        },
                        new
                        {
                            Id = new Guid("4c062ff2-5729-4be9-ac86-398c3bce09b1"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(660),
                            Key = "exercises.bench-press.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(660),
                            Value = "A classic chest exercise focusing on the pectoral muscles. Lie on a bench, lower and lift a barbell or dumbbells to and from your chest."
                        },
                        new
                        {
                            Id = new Guid("ea130353-f8fa-4aa7-b434-ce13111c4642"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(670),
                            Key = "exercises.bench-press.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(670),
                            Value = "Bench-press je klasický cvik pro posílení hrudníku, tricepse a delt. "
                        },
                        new
                        {
                            Id = new Guid("3e7c55a0-1137-48b7-b0c9-7e3a0f1dad0a"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(670),
                            Key = "exercises.lunge.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(670),
                            Value = "Lunge"
                        },
                        new
                        {
                            Id = new Guid("f0fb793f-043e-4a98-b8c0-979df4fd2a1d"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(670),
                            Key = "exercises.lunge.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(670),
                            Value = "Výpad"
                        },
                        new
                        {
                            Id = new Guid("d3ef5b53-a133-4a2b-a117-b59fae2f4a8b"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(680),
                            Key = "exercises.lunge.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(680),
                            Value = "LUNGE"
                        },
                        new
                        {
                            Id = new Guid("2bc30fd7-22dc-4bbe-8a8d-b496326a1951"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(680),
                            Key = "exercises.lunge.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(680),
                            Value = "VYPAD"
                        },
                        new
                        {
                            Id = new Guid("1e76e74b-9696-4fdb-ac7e-403e64c1688a"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(680),
                            Key = "exercises.lunge.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(680),
                            Value = "A lower body exercise targeting the legs and glutes. Take a step forward with one leg, lower your body until both knees form right angles, then return to the starting position."
                        },
                        new
                        {
                            Id = new Guid("c79e4073-0c22-49af-bd3c-3aca311114dc"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(690),
                            Key = "exercises.lunge.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(690),
                            Value = "Výpad je cvik na dolní část těla, střídavým krokem dopředu a poklesem kolena k zemi."
                        },
                        new
                        {
                            Id = new Guid("4edd962f-f6c2-4625-a172-5f81f8668ddb"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(690),
                            Key = "exercises.push-up.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(690),
                            Value = "Push up"
                        },
                        new
                        {
                            Id = new Guid("a0016462-8240-4dbe-bf22-65e6fc7c47ff"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(700),
                            Key = "exercises.push-up.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(700),
                            Value = "Klik"
                        },
                        new
                        {
                            Id = new Guid("fd94178d-365a-4d37-9b1c-c42525438fdd"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(700),
                            Key = "exercises.push-up.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(700),
                            Value = "PUSHUP"
                        },
                        new
                        {
                            Id = new Guid("f93acc8c-3477-4045-bc2a-152f2ac10403"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(700),
                            Key = "exercises.push-up.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(700),
                            Value = "KLIK"
                        },
                        new
                        {
                            Id = new Guid("9ccc66af-b0b4-4891-823c-1ebf7fa356fc"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(710),
                            Key = "exercises.push-up.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(710),
                            Value = "A versatile exercise engaging the chest, shoulders, and triceps. Start in a plank position, lower your body to the ground, and push back up."
                        },
                        new
                        {
                            Id = new Guid("670e641a-986c-4a4a-a801-8dbfa3d2aabd"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(710),
                            Key = "exercises.push-up.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(710),
                            Value = "Kliky jsou cvik na posílení horní části těla, zvláště hrudníku, tricepsů a deltových svalů. Provádí se opakováním zvedání a spouštění těla, kdy se opíráte o ruce na zemi a tlačíte se nahoru a dolů."
                        },
                        new
                        {
                            Id = new Guid("e6719f8d-ba13-4433-ace7-b660f53c7481"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(710),
                            Key = "exercises.curl.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(710),
                            Value = "Bicep curl"
                        },
                        new
                        {
                            Id = new Guid("8907921d-3237-4370-9336-ac22e3207c5f"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(720),
                            Key = "exercises.curl.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(720),
                            Value = "Bicepsový zdvih"
                        },
                        new
                        {
                            Id = new Guid("fa0928f6-bc29-42af-a6ea-f48061f5c3a8"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(720),
                            Key = "exercises.curl.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(720),
                            Value = "BICEPCURL"
                        },
                        new
                        {
                            Id = new Guid("30e276b3-23bb-4829-89b9-1b90519df263"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(720),
                            Key = "exercises.curl.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(720),
                            Value = "BICEPSOVYZDVIH"
                        },
                        new
                        {
                            Id = new Guid("09dc677a-6f66-4a7a-8604-54a5c88bfcc3"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(730),
                            Key = "exercises.curl.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(730),
                            Value = "An isolation exercise for the biceps. Stand with weights in hand, palms facing forward, and curl the weights towards your shoulders by bending at the elbows."
                        },
                        new
                        {
                            Id = new Guid("30c46a63-399c-445f-a048-057a59da9a51"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(730),
                            Key = "exercises.curl.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 6, 19, 81, DateTimeKind.Utc).AddTicks(730),
                            Value = "Bicepsový zdvih cílí na posílení bicepsů a vykonává se zdvihem váhy směrem k ramenům při ohnutí v loktech."
                        });
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Users.HeightLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Uid");

                    b.ToTable("Heights");
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Users.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Users.WeightLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Uid");

                    b.ToTable("Weights");
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Workouts.ActivityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RepetitionsCount")
                        .HasColumnType("int");

                    b.Property<int>("SetsCount")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Workouts.WorkoutEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("VerifiedAtGymId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Workouts.ActivityEntity", b =>
                {
                    b.HasOne("FormUp.Api.Features.v1.Exercises.ExerciseEntity", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormUp.Api.Features.v1.Workouts.WorkoutEntity", "Workout")
                        .WithMany("Activities")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Workouts.WorkoutEntity", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
