// <auto-generated />
using System;
using FormUp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormUp.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240112171618_RemoveGeolocationEntity")]
    partial class RemoveGeolocationEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormUp.Api.Features.v1.Exercises.ExerciseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("95640e86-3b1f-475f-b6a4-04aa9aa95fa6"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(5860),
                            Description = "exercises.squat.description",
                            ImageURL = "https://legionathletics.com/wp-content/uploads/2019/05/arnold-squat.jpg",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(5860),
                            Name = "exercises.squat.name",
                            NormalizedName = "exercises.squat.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("fa8378b2-66c4-4ea8-a14a-5486421727d5"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(5860),
                            Description = "exercises.dead-lift.description",
                            ImageURL = "https://miro.medium.com/v2/resize:fit:1024/0*UkQCo1eLsXjoXn4v.jpg",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(5860),
                            Name = "exercises.dead-lift.name",
                            NormalizedName = "exercises.dead-lift.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("ff78d2e7-d3a5-49f6-a9ef-2476eb272343"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(5870),
                            Description = "exercises.shoulder-press.description",
                            ImageURL = "https://legionathletics.com/wp-content/uploads/2023/10/Dumbbell-Shoulder-Press-before-after.png",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(5870),
                            Name = "exercises.shoulder-press.name",
                            NormalizedName = "exercises.shoulder-press.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("2fb5dd3d-33f1-4df0-8d3d-76ebccf624fe"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(5870),
                            Description = "exercises.pull-up.description",
                            ImageURL = "https://hips.hearstapps.com/hmg-prod/images/mh0418-fit-pul-01-1558551798.jpg?crop=0.749xw:1.00xh;0.251xw,0&resize=1200:*",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(5870),
                            Name = "exercises.pull-up.name",
                            NormalizedName = "exercises.pull-up.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("8199994a-2c4a-417a-86e6-b2143c38e4d6"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(5870),
                            Description = "exercises.dip.description",
                            ImageURL = "https://www.muscleandfitness.com/wp-content/uploads/2018/07/1109-dip.jpg?w=800&quality=86&strip=all",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(5870),
                            Name = "exercises.dip.name",
                            NormalizedName = "exercises.dip.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("5443f8f5-b9dc-4afa-9835-09f730a8219b"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(5880),
                            Description = "exercises.bench-press.description",
                            ImageURL = "https://caliberstrong.com/wp-content/uploads/2020/04/how-to-bench-press.jpg",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(5880),
                            Name = "exercises.bench-press.name",
                            NormalizedName = "exercises.bench-press.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("fb51932c-7457-4dc8-afef-0b8d613b09fd"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(5880),
                            Description = "exercises.lunge.description",
                            ImageURL = "https://hortonbarbell.com/wp-content/uploads/2022/05/Dumbbell-Lunge.png",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(5880),
                            Name = "exercises.lunge.name",
                            NormalizedName = "exercises.lunge.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("235db024-23e0-4383-8392-24051d34dab7"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(5880),
                            Description = "exercises.push-up.description",
                            ImageURL = "https://www.fitnesseducation.edu.au/wp-content/uploads/2017/03/Pushups.jpg",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(5880),
                            Name = "exercises.push-up.name",
                            NormalizedName = "exercises.push-up.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("6f714844-8a78-40b7-9cc3-78291fcb0864"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(5890),
                            Description = "exercises.curl.description",
                            ImageURL = "https://hortonbarbell.com/wp-content/uploads/2023/01/How-To-Do-Tempo-Bicep-Curls.png",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(5890),
                            Name = "exercises.curl.name",
                            NormalizedName = "exercises.curl.normalized-name"
                        });
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Gyms.GymEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gyms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f425b9d-1539-4111-ad2c-eec94c75c581"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6240),
                            Latitude = 49.178859520009325,
                            Longitude = 16.59588166754828,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6240),
                            Name = "Posilovna Velký Průvan"
                        },
                        new
                        {
                            Id = new Guid("d7551e02-3de6-43c3-a1ae-378f885c10c2"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6250),
                            Latitude = 49.179083949535297,
                            Longitude = 16.596503940037902,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6250),
                            Name = "Posilovna Malý Průvan"
                        },
                        new
                        {
                            Id = new Guid("de3fea2e-aebd-4191-9637-1c70a4cf4382"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6250),
                            Latitude = 49.177089060496634,
                            Longitude = 16.606190093594201,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6250),
                            Name = "AZ Fitness"
                        },
                        new
                        {
                            Id = new Guid("cec5bd39-ccd0-4713-a5b0-ebfbaa9e8563"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6250),
                            Latitude = 49.181262112264804,
                            Longitude = 16.60282245697524,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6260),
                            Name = "NewPark Gym"
                        },
                        new
                        {
                            Id = new Guid("42fe9642-3cf5-41e1-91f7-4297df327e45"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6260),
                            Latitude = 49.180330210607991,
                            Longitude = 16.606384581697789,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6260),
                            Name = "Energy Fitness Club"
                        },
                        new
                        {
                            Id = new Guid("efbd8fc8-9f68-4733-b21b-dd01271ed4d8"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6260),
                            Latitude = 49.215051402565855,
                            Longitude = 16.609402145470618,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6260),
                            Name = "Hulk Gym"
                        },
                        new
                        {
                            Id = new Guid("7e3c56c9-1efe-46f5-a62b-badc86c90853"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6260),
                            Latitude = 49.212976899683049,
                            Longitude = 16.609015907373617,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6270),
                            Name = "Fitness Boby"
                        },
                        new
                        {
                            Id = new Guid("16a5d582-4405-44a6-a439-0e2b45f81725"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6270),
                            Latitude = 49.218555432690493,
                            Longitude = 16.624250854578833,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6270),
                            Name = "Blackfield Gym"
                        },
                        new
                        {
                            Id = new Guid("488b1d32-2b0f-4c75-88b5-aa7aa0b0787f"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6270),
                            Latitude = 49.190492694739753,
                            Longitude = 16.617386769256324,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6270),
                            Name = "Form Factory Fitness Club Vlněna"
                        },
                        new
                        {
                            Id = new Guid("29a68557-6522-402a-9758-9edf58ad02ec"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6280),
                            Latitude = 49.208489226784764,
                            Longitude = 16.605422062883459,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6280),
                            Name = "Form Factory Fitness Club Lužánky"
                        });
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Translations.TranslationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Locale", "Key");

                    b.ToTable("Translations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3216a9d4-b033-4511-b981-7f9d83633dda"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6000),
                            Key = "exercises.squat.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6000),
                            Value = "Squat"
                        },
                        new
                        {
                            Id = new Guid("1e8f0d9e-4a6b-4370-8d7d-4474af5586b6"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6000),
                            Key = "exercises.squat.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6000),
                            Value = "Dřep"
                        },
                        new
                        {
                            Id = new Guid("4a50b1a0-df08-48a6-a43e-c492f8bd7fc7"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6010),
                            Key = "exercises.squat.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6010),
                            Value = "SQUAT"
                        },
                        new
                        {
                            Id = new Guid("0463c1c3-8f97-4c29-a878-c4d8b2227edf"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6010),
                            Key = "exercises.squat.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6010),
                            Value = "DREP"
                        },
                        new
                        {
                            Id = new Guid("25abb841-fcf2-42fb-9b43-5d3aaf1640c6"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6010),
                            Key = "exercises.squat.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6010),
                            Value = "A fundamental lower body exercise targeting the legs, hamstrings, and glutes. Stand with feet shoulder-width apart, lower your body by bending your knees, and return to the starting position."
                        },
                        new
                        {
                            Id = new Guid("c563f5f4-07e8-4729-9177-6b6f0afa392c"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6020),
                            Key = "exercises.squat.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6020),
                            Value = "Dřep posiluje dolní část těla, především nohy, hamstrings a hýždě. Vykonává se stáním s váhou na ramenou a poklesem do pravého úhlu v kolenou."
                        },
                        new
                        {
                            Id = new Guid("e474e447-9ad5-4f1f-9906-a7c44361a298"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6020),
                            Key = "exercises.dead-lift.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6020),
                            Value = "Dead-lift"
                        },
                        new
                        {
                            Id = new Guid("3850c017-f071-4b66-a8d2-56ff36cf47be"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6020),
                            Key = "exercises.dead-lift.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6020),
                            Value = "Mrtvý tah"
                        },
                        new
                        {
                            Id = new Guid("a8e82997-9f5a-497a-a8c7-d93d63659f6f"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6030),
                            Key = "exercises.dead-lift.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6030),
                            Value = "DEADLIFT"
                        },
                        new
                        {
                            Id = new Guid("0ee916e3-c745-47ca-9b8b-3f0008f78517"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6030),
                            Key = "exercises.dead-lift.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6030),
                            Value = "MRTVYTAH"
                        },
                        new
                        {
                            Id = new Guid("c0db9fb0-37f1-4a0b-bb63-3c1c4f72c3d1"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6030),
                            Key = "exercises.dead-lift.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6030),
                            Value = "A compound exercise for overall strength, focusing on the back, glutes, hamstrings, and lower back. Start with the weight on the ground, hinge at the hips, lift the weight by straightening your hips and knees."
                        },
                        new
                        {
                            Id = new Guid("2d5a0c6f-28e6-459d-ad36-3a92c671142e"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6040),
                            Key = "exercises.dead-lift.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6040),
                            Value = "Mrtvý tah je cvik na posílení zad, hýždí a hamstringů, provedený ohnutím v pase a zdvihem váhy z podlahy s udržením rovné páteře."
                        },
                        new
                        {
                            Id = new Guid("14040039-e74f-4978-bf90-8a5fe5832b35"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6040),
                            Key = "exercises.shoulder-press.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6040),
                            Value = "Shoulder press"
                        },
                        new
                        {
                            Id = new Guid("9a29eaf0-4ce7-45cb-8035-8bc3b885856f"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6040),
                            Key = "exercises.shoulder-press.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6040),
                            Value = "Tlak na ramena"
                        },
                        new
                        {
                            Id = new Guid("6268d648-552b-4596-a2fc-4ed8c1636f32"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6050),
                            Key = "exercises.shoulder-press.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6050),
                            Value = "SHOULDERPRESS"
                        },
                        new
                        {
                            Id = new Guid("3223083b-3249-40a1-97cb-69ac47ea9712"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6050),
                            Key = "exercises.shoulder-press.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6050),
                            Value = "TLAKNARAMENA"
                        },
                        new
                        {
                            Id = new Guid("46435ef8-e444-4b34-83be-95890bc5c151"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6050),
                            Key = "exercises.shoulder-press.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6050),
                            Value = "An upper body exercise concentrating on shoulder muscles. Whether sitting or standing, press weights or other resistance overhead, emphasizing controlled movements."
                        },
                        new
                        {
                            Id = new Guid("c9fbdc24-0336-4f96-8646-f21ceb499fda"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6050),
                            Key = "exercises.shoulder-press.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6050),
                            Value = "Tlaky na ramena zaměřují se na posílení ramenních svalů a vykonávají se tlačením činek nad hlavu."
                        },
                        new
                        {
                            Id = new Guid("30cf6252-e5e1-4c90-89f9-1cd5e553fabb"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6060),
                            Key = "exercises.pull-up.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6060),
                            Value = "Pull up"
                        },
                        new
                        {
                            Id = new Guid("978c35dc-0a18-4aa5-bc6f-2712d13be1e0"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6060),
                            Key = "exercises.pull-up.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6060),
                            Value = "Shyb"
                        },
                        new
                        {
                            Id = new Guid("27736998-f81c-4a01-a5c4-33533d08d87b"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6060),
                            Key = "exercises.pull-up.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6070),
                            Value = "PULLUP"
                        },
                        new
                        {
                            Id = new Guid("e69983d3-d3db-491e-a12a-76a2d96cd51b"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6070),
                            Key = "exercises.pull-up.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6070),
                            Value = "SHYB"
                        },
                        new
                        {
                            Id = new Guid("74834118-a803-4374-9124-7118cc09f205"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6070),
                            Key = "exercises.pull-up.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6070),
                            Value = "An effective upper body exercise primarily targeting the back and biceps. Hang from a bar with palms facing away, pull your body up until your chin passes the bar, and lower back down."
                        },
                        new
                        {
                            Id = new Guid("58b21240-7e65-474a-a768-87555314a288"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6070),
                            Key = "exercises.pull-up.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6070),
                            Value = "Shyb je izolovaný cvik pro tricepsy, provádí se zvedáním váhy pomocí prodloužení paže."
                        },
                        new
                        {
                            Id = new Guid("594eb423-6e52-477f-8fff-d2810837a2af"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6080),
                            Key = "exercises.dip.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6080),
                            Value = "Dip"
                        },
                        new
                        {
                            Id = new Guid("847ab7dc-db1a-4730-8403-bf0726ea059a"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6080),
                            Key = "exercises.dip.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6080),
                            Value = "Klik na bradlech"
                        },
                        new
                        {
                            Id = new Guid("dd05513a-fa27-4722-ba6c-60a35feac113"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6080),
                            Key = "exercises.dip.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6080),
                            Value = "DIP"
                        },
                        new
                        {
                            Id = new Guid("17c4bf72-d9d3-4004-a32a-5accd6a589ba"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6090),
                            Key = "exercises.dip.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6090),
                            Value = "KLIKNABRADLECH"
                        },
                        new
                        {
                            Id = new Guid("4ba32383-9ef2-42b9-a5b4-d97a54c62c4d"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6090),
                            Key = "exercises.dip.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6090),
                            Value = "An isolation exercise for the triceps and chest. Support yourself on parallel bars, lower your body by bending your elbows, and push back up."
                        },
                        new
                        {
                            Id = new Guid("7500d55e-1e52-4aaa-8fd4-cc40b55a8eb1"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6090),
                            Key = "exercises.dip.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6090),
                            Value = "Kliky na bradlech posilují horní část těla, zejména hrudník, tricepsy a deltové svaly."
                        },
                        new
                        {
                            Id = new Guid("ecadef8c-2b06-487f-9508-ebea7faedaa0"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6100),
                            Key = "exercises.bench-press.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6100),
                            Value = "Bench press"
                        },
                        new
                        {
                            Id = new Guid("ca689ebb-c14a-4f79-97b8-48030bde49b9"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6100),
                            Key = "exercises.bench-press.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6100),
                            Value = "Bench press"
                        },
                        new
                        {
                            Id = new Guid("f22b5184-fa58-4793-abde-7dbd39e1cdca"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6100),
                            Key = "exercises.bench-press.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6100),
                            Value = "BENCHPRESS"
                        },
                        new
                        {
                            Id = new Guid("c456cfb8-cb85-482d-b392-4bc8ad0c8f03"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6110),
                            Key = "exercises.bench-press.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6110),
                            Value = "BENCHPRESS"
                        },
                        new
                        {
                            Id = new Guid("de1f9a77-17c2-4e34-a3f3-cde8908a7e67"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6110),
                            Key = "exercises.bench-press.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6110),
                            Value = "A classic chest exercise focusing on the pectoral muscles. Lie on a bench, lower and lift a barbell or dumbbells to and from your chest."
                        },
                        new
                        {
                            Id = new Guid("7c22d816-17e8-4bee-9abe-9ec45f32eb44"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6110),
                            Key = "exercises.bench-press.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6110),
                            Value = "Bench-press je klasický cvik pro posílení hrudníku, tricepse a delt. "
                        },
                        new
                        {
                            Id = new Guid("e6bbed0b-5d4c-410a-85fe-ee52d704a7dd"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6120),
                            Key = "exercises.lunge.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6120),
                            Value = "Lunge"
                        },
                        new
                        {
                            Id = new Guid("0070e103-da17-48c9-88ae-4ba94ace0650"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6120),
                            Key = "exercises.lunge.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6120),
                            Value = "Výpad"
                        },
                        new
                        {
                            Id = new Guid("527d0cbd-0749-4896-8c75-090860d75673"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6120),
                            Key = "exercises.lunge.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6120),
                            Value = "LUNGE"
                        },
                        new
                        {
                            Id = new Guid("6a754431-7a82-4282-8b34-b02a7a1f7bad"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6130),
                            Key = "exercises.lunge.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6130),
                            Value = "VYPAD"
                        },
                        new
                        {
                            Id = new Guid("caa4f322-eb68-499f-8e23-ba1a4edb766e"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6130),
                            Key = "exercises.lunge.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6130),
                            Value = "A lower body exercise targeting the legs and glutes. Take a step forward with one leg, lower your body until both knees form right angles, then return to the starting position."
                        },
                        new
                        {
                            Id = new Guid("a3305da5-4f5c-4ec6-8d13-9266fe0cb5f1"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6130),
                            Key = "exercises.lunge.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6130),
                            Value = "Výpad je cvik na dolní část těla, střídavým krokem dopředu a poklesem kolena k zemi."
                        },
                        new
                        {
                            Id = new Guid("0ec263a6-834d-4cf1-b768-4b303df83e38"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6140),
                            Key = "exercises.push-up.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6140),
                            Value = "Push up"
                        },
                        new
                        {
                            Id = new Guid("7f03c884-ec07-4b21-bbed-dc0556934a86"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6140),
                            Key = "exercises.push-up.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6140),
                            Value = "Klik"
                        },
                        new
                        {
                            Id = new Guid("52d6cb36-aba8-410f-962d-82831668d84d"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6140),
                            Key = "exercises.push-up.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6140),
                            Value = "PUSHUP"
                        },
                        new
                        {
                            Id = new Guid("022cf0b1-a982-4275-af79-1f451d578c41"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6150),
                            Key = "exercises.push-up.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6150),
                            Value = "KLIK"
                        },
                        new
                        {
                            Id = new Guid("b6a6e076-d6cd-4b96-89d7-89e149f78b38"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6150),
                            Key = "exercises.push-up.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6150),
                            Value = "A versatile exercise engaging the chest, shoulders, and triceps. Start in a plank position, lower your body to the ground, and push back up."
                        },
                        new
                        {
                            Id = new Guid("398e4659-c853-4cad-8470-007e3d2fd8c2"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6150),
                            Key = "exercises.push-up.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6150),
                            Value = "Kliky jsou cvik na posílení horní části těla, zvláště hrudníku, tricepsů a deltových svalů. Provádí se opakováním zvedání a spouštění těla, kdy se opíráte o ruce na zemi a tlačíte se nahoru a dolů."
                        },
                        new
                        {
                            Id = new Guid("df1f5582-1189-47c5-9b67-51444b625015"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6160),
                            Key = "exercises.curl.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6160),
                            Value = "Bicep curl"
                        },
                        new
                        {
                            Id = new Guid("0e777278-f097-49d1-ac7f-18e9c0291a78"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6160),
                            Key = "exercises.curl.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6160),
                            Value = "Bicepsový zdvih"
                        },
                        new
                        {
                            Id = new Guid("fdb22b08-d9f1-4698-805c-77e198575f25"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6160),
                            Key = "exercises.curl.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6160),
                            Value = "BICEPCURL"
                        },
                        new
                        {
                            Id = new Guid("a203dc84-7719-4fab-ba7e-b3403bc6a4dc"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6170),
                            Key = "exercises.curl.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6170),
                            Value = "BICEPSOVYZDVIH"
                        },
                        new
                        {
                            Id = new Guid("54e097e8-4764-4605-9945-544697364cba"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6170),
                            Key = "exercises.curl.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6170),
                            Value = "An isolation exercise for the biceps. Stand with weights in hand, palms facing forward, and curl the weights towards your shoulders by bending at the elbows."
                        },
                        new
                        {
                            Id = new Guid("4fdeb35d-a3be-4e1d-8870-c99a7a3e47f2"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6170),
                            Key = "exercises.curl.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 16, 17, 577, DateTimeKind.Utc).AddTicks(6170),
                            Value = "Bicepsový zdvih cílí na posílení bicepsů a vykonává se zdvihem váhy směrem k ramenům při ohnutí v loktech."
                        });
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Users.HeightLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Uid");

                    b.ToTable("Heights");
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Users.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Users.WeightLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Uid");

                    b.ToTable("Weights");
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Workouts.ActivityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RepetitionsCount")
                        .HasColumnType("int");

                    b.Property<int>("SetsCount")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<Guid?>("WorkoutEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutEntityId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Workouts.WorkoutEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("VerifiedAtGymId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Workouts.ActivityEntity", b =>
                {
                    b.HasOne("FormUp.Api.Features.v1.Exercises.ExerciseEntity", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormUp.Api.Features.v1.Workouts.WorkoutEntity", null)
                        .WithMany("Activities")
                        .HasForeignKey("WorkoutEntityId");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Workouts.WorkoutEntity", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
