// <auto-generated />
using System;
using FormUp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormUp.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240111130151_AddMoreInfoToExercises")]
    partial class AddMoreInfoToExercises
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormUp.Api.Common.Persistence.GeolocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Geolocations");
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Exercises.ExerciseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a544b9f-cb83-4dd5-a6e6-3d7dafd1c3f9"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6320),
                            Description = "exercises.squat.description",
                            ImageURL = "https://legionathletics.com/wp-content/uploads/2019/05/arnold-squat.jpg",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6320),
                            Name = "exercises.squat.name",
                            NormalizedName = "exercises.squat.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("cb68be57-94ce-4149-8d0e-7db6c7706b5a"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6330),
                            Description = "exercises.dead-lift.description",
                            ImageURL = "https://miro.medium.com/v2/resize:fit:1024/0*UkQCo1eLsXjoXn4v.jpg",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6330),
                            Name = "exercises.dead-lift.name",
                            NormalizedName = "exercises.dead-lift.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("f478d873-d2e7-4deb-8f15-6d5bfdde550b"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6330),
                            Description = "exercises.shoulder-press.description",
                            ImageURL = "https://legionathletics.com/wp-content/uploads/2023/10/Dumbbell-Shoulder-Press-before-after.png",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6330),
                            Name = "exercises.shoulder-press.name",
                            NormalizedName = "exercises.shoulder-press.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("47bad8bd-6116-4824-b20a-970555533098"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6340),
                            Description = "exercises.pull-up.description",
                            ImageURL = "https://hips.hearstapps.com/hmg-prod/images/mh0418-fit-pul-01-1558551798.jpg?crop=0.749xw:1.00xh;0.251xw,0&resize=1200:*",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6340),
                            Name = "exercises.pull-up.name",
                            NormalizedName = "exercises.pull-up.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("85d567ed-2ecf-4ccd-acab-0110c838bbc9"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6340),
                            Description = "exercises.dip.description",
                            ImageURL = "https://www.muscleandfitness.com/wp-content/uploads/2018/07/1109-dip.jpg?w=800&quality=86&strip=all",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6340),
                            Name = "exercises.dip.name",
                            NormalizedName = "exercises.dip.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("ea176a07-39e4-439c-a3be-08a1ffee51c8"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6350),
                            Description = "exercises.bench-press.description",
                            ImageURL = "https://caliberstrong.com/wp-content/uploads/2020/04/how-to-bench-press.jpg",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6350),
                            Name = "exercises.bench-press.name",
                            NormalizedName = "exercises.bench-press.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("fe7e5db1-ae3c-4087-bd0d-4da92193ea93"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6350),
                            Description = "exercises.lunge.description",
                            ImageURL = "https://hortonbarbell.com/wp-content/uploads/2022/05/Dumbbell-Lunge.png",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6350),
                            Name = "exercises.lunge.name",
                            NormalizedName = "exercises.lunge.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("6eeb8a04-3209-4e17-bc4e-52349e1b9678"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6350),
                            Description = "exercises.push-up.description",
                            ImageURL = "https://www.fitnesseducation.edu.au/wp-content/uploads/2017/03/Pushups.jpg",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6350),
                            Name = "exercises.push-up.name",
                            NormalizedName = "exercises.push-up.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("3402086c-4353-4e4d-b1c0-8a9da1888d96"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6360),
                            Description = "exercises.curl.description",
                            ImageURL = "https://hortonbarbell.com/wp-content/uploads/2023/01/How-To-Do-Tempo-Bicep-Curls.png",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6360),
                            Name = "exercises.curl.name",
                            NormalizedName = "exercises.curl.normalized-name"
                        });
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Gyms.GymEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gyms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("42994c66-5a02-45b7-8545-e3323db1120c"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6730),
                            Latitude = 49.178859520009325,
                            Longitude = 16.59588166754828,
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6730),
                            Name = "Posilovna Velký Průvan"
                        },
                        new
                        {
                            Id = new Guid("e64f70fc-fffe-42ea-8ae1-43cc5ce5c9a0"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6730),
                            Latitude = 49.179083949535297,
                            Longitude = 16.596503940037902,
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6730),
                            Name = "Posilovna Malý Průvan"
                        },
                        new
                        {
                            Id = new Guid("40fc84f3-a907-44fd-8a3f-b00829aff78d"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6740),
                            Latitude = 49.177089060496634,
                            Longitude = 16.606190093594201,
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6740),
                            Name = "AZ Fitness"
                        },
                        new
                        {
                            Id = new Guid("d69c2bbf-052d-4088-9729-f7ea854e0d47"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6740),
                            Latitude = 49.181262112264804,
                            Longitude = 16.60282245697524,
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6740),
                            Name = "NewPark Gym"
                        },
                        new
                        {
                            Id = new Guid("10e4b565-bc4e-49ef-bdb4-a528d7d65f39"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6740),
                            Latitude = 49.180330210607991,
                            Longitude = 16.606384581697789,
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6740),
                            Name = "Energy Fitness Club"
                        },
                        new
                        {
                            Id = new Guid("02a0d371-de5a-4f6f-80e6-8c8a04e8cafb"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6750),
                            Latitude = 49.215051402565855,
                            Longitude = 16.609402145470618,
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6750),
                            Name = "Hulk Gym"
                        },
                        new
                        {
                            Id = new Guid("3e9fefef-6515-44c7-b2e4-e12d7df7ac5f"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6750),
                            Latitude = 49.212976899683049,
                            Longitude = 16.609015907373617,
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6750),
                            Name = "Fitness Boby"
                        },
                        new
                        {
                            Id = new Guid("06ede792-e5b9-4575-9c25-37d6095e6871"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6750),
                            Latitude = 49.218555432690493,
                            Longitude = 16.624250854578833,
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6750),
                            Name = "Blackfield Gym"
                        },
                        new
                        {
                            Id = new Guid("a80750cf-e4b1-4838-9a8b-3376b7cde476"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6760),
                            Latitude = 49.190492694739753,
                            Longitude = 16.617386769256324,
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6760),
                            Name = "Form Factory Fitness Club Vlněna"
                        },
                        new
                        {
                            Id = new Guid("2064c892-395c-4806-a005-5a3cbe2607c2"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6760),
                            Latitude = 49.208489226784764,
                            Longitude = 16.605422062883459,
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6760),
                            Name = "Form Factory Fitness Club Lužánky"
                        });
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Translations.TranslationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Locale", "Key");

                    b.ToTable("Translations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ef6bc65-b7d6-444a-8995-5e99dd0d7f0d"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6470),
                            Key = "exercises.squat.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6470),
                            Value = "Squat"
                        },
                        new
                        {
                            Id = new Guid("58e24599-6323-4590-8b4e-e9121f9f41b9"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6470),
                            Key = "exercises.squat.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6470),
                            Value = "Dřep"
                        },
                        new
                        {
                            Id = new Guid("30c045cb-c334-4376-abe8-e65f6d58c729"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6470),
                            Key = "exercises.squat.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6470),
                            Value = "SQUAT"
                        },
                        new
                        {
                            Id = new Guid("60234e5a-3b4f-49df-b42b-8728f0cfe510"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6480),
                            Key = "exercises.squat.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6480),
                            Value = "DREP"
                        },
                        new
                        {
                            Id = new Guid("1e131325-e252-4fcb-93f4-666730d508ef"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6480),
                            Key = "exercises.squat.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6480),
                            Value = "A fundamental lower body exercise targeting the legs, hamstrings, and glutes. Stand with feet shoulder-width apart, lower your body by bending your knees, and return to the starting position."
                        },
                        new
                        {
                            Id = new Guid("e1dbb834-c08b-488f-804c-bc5f59fe0ede"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6480),
                            Key = "exercises.squat.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6480),
                            Value = "Dřep posiluje dolní část těla, především nohy, hamstrings a hýždě. Vykonává se stáním s váhou na ramenou a poklesem do pravého úhlu v kolenou."
                        },
                        new
                        {
                            Id = new Guid("d6e3977b-87d8-49c8-b6b5-67f2357a2328"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6490),
                            Key = "exercises.dead-lift.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6490),
                            Value = "Dead-lift"
                        },
                        new
                        {
                            Id = new Guid("00ca0392-333d-42a7-a545-4c6212e087ef"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6490),
                            Key = "exercises.dead-lift.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6490),
                            Value = "Mrtvý tah"
                        },
                        new
                        {
                            Id = new Guid("34b6ec59-5a9e-43f6-b3a9-038e089479c9"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6490),
                            Key = "exercises.dead-lift.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6490),
                            Value = "DEADLIFT"
                        },
                        new
                        {
                            Id = new Guid("437b14d0-8577-4a34-964c-d04204273c46"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6500),
                            Key = "exercises.dead-lift.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6500),
                            Value = "MRTVYTAH"
                        },
                        new
                        {
                            Id = new Guid("b7f6ecf4-b1fb-42c3-a818-8b152b96aab4"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6500),
                            Key = "exercises.dead-lift.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6500),
                            Value = "A compound exercise for overall strength, focusing on the back, glutes, hamstrings, and lower back. Start with the weight on the ground, hinge at the hips, lift the weight by straightening your hips and knees."
                        },
                        new
                        {
                            Id = new Guid("62cf4746-16a7-4a00-9ffd-3cb473639b06"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6500),
                            Key = "exercises.dead-lift.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6500),
                            Value = "Mrtvý tah je cvik na posílení zad, hýždí a hamstringů, provedený ohnutím v pase a zdvihem váhy z podlahy s udržením rovné páteře."
                        },
                        new
                        {
                            Id = new Guid("5ef99cf2-e0d9-4967-8485-8a725d7a21f6"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6510),
                            Key = "exercises.shoulder-press.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6510),
                            Value = "Shoulder press"
                        },
                        new
                        {
                            Id = new Guid("f61878f3-2e99-4e80-8e6e-619775dbf9a9"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6510),
                            Key = "exercises.shoulder-press.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6510),
                            Value = "Tlak na ramena"
                        },
                        new
                        {
                            Id = new Guid("5221f95f-6dd3-48f3-9a13-ff7650da4ad8"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6510),
                            Key = "exercises.shoulder-press.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6510),
                            Value = "SHOULDERPRESS"
                        },
                        new
                        {
                            Id = new Guid("a19baf8e-bd04-4007-b108-f3ec64cc8ab7"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6520),
                            Key = "exercises.shoulder-press.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6520),
                            Value = "TLAKNARAMENA"
                        },
                        new
                        {
                            Id = new Guid("4415e57c-4073-4f52-82be-7e8142753193"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6520),
                            Key = "exercises.shoulder-press.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6520),
                            Value = "An upper body exercise concentrating on shoulder muscles. Whether sitting or standing, press weights or other resistance overhead, emphasizing controlled movements."
                        },
                        new
                        {
                            Id = new Guid("a3eca4f8-4e5d-48fb-9813-7f6a943950c7"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6520),
                            Key = "exercises.shoulder-press.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6520),
                            Value = "Tlaky na ramena zaměřují se na posílení ramenních svalů a vykonávají se tlačením činek nad hlavu."
                        },
                        new
                        {
                            Id = new Guid("fd30a84a-1874-49e5-b1be-7bfe1f722d9c"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6530),
                            Key = "exercises.pull-up.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6530),
                            Value = "Pull up"
                        },
                        new
                        {
                            Id = new Guid("57d7b225-8944-4867-a5dc-74be46bbbe17"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6530),
                            Key = "exercises.pull-up.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6530),
                            Value = "Shyb"
                        },
                        new
                        {
                            Id = new Guid("bef35816-9774-4e2c-829d-08412d305bdf"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6530),
                            Key = "exercises.pull-up.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6530),
                            Value = "PULLUP"
                        },
                        new
                        {
                            Id = new Guid("7ae636ba-4c52-4305-b5c9-dfb08aa166ee"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6540),
                            Key = "exercises.pull-up.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6540),
                            Value = "SHYB"
                        },
                        new
                        {
                            Id = new Guid("b3be6085-abf3-47b8-a779-6b3dc7715104"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6540),
                            Key = "exercises.pull-up.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6540),
                            Value = "An effective upper body exercise primarily targeting the back and biceps. Hang from a bar with palms facing away, pull your body up until your chin passes the bar, and lower back down."
                        },
                        new
                        {
                            Id = new Guid("9d20c4b6-28f6-4bb1-955d-aa402710a289"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6540),
                            Key = "exercises.pull-up.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6540),
                            Value = "Shyb je izolovaný cvik pro tricepsy, provádí se zvedáním váhy pomocí prodloužení paže."
                        },
                        new
                        {
                            Id = new Guid("de8d7db2-1afa-4729-a529-5c36ef8d09d5"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6540),
                            Key = "exercises.dip.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6550),
                            Value = "Dip"
                        },
                        new
                        {
                            Id = new Guid("8bff3351-c3e9-4974-b72b-ad3224d69a54"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6550),
                            Key = "exercises.dip.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6550),
                            Value = "Klik na bradlech"
                        },
                        new
                        {
                            Id = new Guid("94365bd2-9438-4da4-bc93-55932180e023"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6550),
                            Key = "exercises.dip.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6550),
                            Value = "DIP"
                        },
                        new
                        {
                            Id = new Guid("ec96b70d-088e-495b-bf7e-a0dc449a2a86"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6550),
                            Key = "exercises.dip.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6560),
                            Value = "KLIKNABRADLECH"
                        },
                        new
                        {
                            Id = new Guid("16eeb543-fea1-4d58-98b9-424b44f72213"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6560),
                            Key = "exercises.dip.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6560),
                            Value = "An isolation exercise for the triceps and chest. Support yourself on parallel bars, lower your body by bending your elbows, and push back up."
                        },
                        new
                        {
                            Id = new Guid("5dca569b-666b-4e05-b1ba-64b2e7ea2e20"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6560),
                            Key = "exercises.dip.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6560),
                            Value = "Kliky na bradlech posilují horní část těla, zejména hrudník, tricepsy a deltové svaly."
                        },
                        new
                        {
                            Id = new Guid("55189d16-106d-4389-ba7e-5c3e430e4d14"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6560),
                            Key = "exercises.bench-press.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6560),
                            Value = "Bench press"
                        },
                        new
                        {
                            Id = new Guid("b685fb3a-5350-450a-bdba-b94dabb76e9e"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6570),
                            Key = "exercises.bench-press.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6570),
                            Value = "Bench press"
                        },
                        new
                        {
                            Id = new Guid("05674422-29af-4c8d-b20c-26468fb934af"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6570),
                            Key = "exercises.bench-press.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6570),
                            Value = "BENCHPRESS"
                        },
                        new
                        {
                            Id = new Guid("e6293cb6-b37d-4e56-9e42-b3a112f41499"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6570),
                            Key = "exercises.bench-press.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6570),
                            Value = "BENCHPRESS"
                        },
                        new
                        {
                            Id = new Guid("aa4d6373-3fb4-4f48-b22c-958ac6d9e2fe"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6580),
                            Key = "exercises.bench-press.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6580),
                            Value = "A classic chest exercise focusing on the pectoral muscles. Lie on a bench, lower and lift a barbell or dumbbells to and from your chest."
                        },
                        new
                        {
                            Id = new Guid("abac62f5-bc79-4292-a6af-98ea017c202c"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6580),
                            Key = "exercises.bench-press.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6580),
                            Value = "Bench-press je klasický cvik pro posílení hrudníku, tricepse a delt. "
                        },
                        new
                        {
                            Id = new Guid("09a168f6-cab3-4dd1-858f-ebc5c0cb7307"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6580),
                            Key = "exercises.lunge.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6580),
                            Value = "Lunge"
                        },
                        new
                        {
                            Id = new Guid("d2307913-6d46-4be2-91fc-3951843da8b7"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6590),
                            Key = "exercises.lunge.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6590),
                            Value = "Výpad"
                        },
                        new
                        {
                            Id = new Guid("17a20bbe-1ddd-4b9a-953f-cc791455169d"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6610),
                            Key = "exercises.lunge.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6610),
                            Value = "LUNGE"
                        },
                        new
                        {
                            Id = new Guid("65f525eb-bb17-4f57-ae5f-547997207968"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6610),
                            Key = "exercises.lunge.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6610),
                            Value = "VYPAD"
                        },
                        new
                        {
                            Id = new Guid("9d8e69e7-6db6-4c49-9ca1-a3439c710e3d"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6610),
                            Key = "exercises.lunge.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6610),
                            Value = "A lower body exercise targeting the legs and glutes. Take a step forward with one leg, lower your body until both knees form right angles, then return to the starting position."
                        },
                        new
                        {
                            Id = new Guid("541fd8cf-65e4-453d-93a5-9c54102ba8dd"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6620),
                            Key = "exercises.lunge.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6620),
                            Value = "Výpad je cvik na dolní část těla, střídavým krokem dopředu a poklesem kolena k zemi."
                        },
                        new
                        {
                            Id = new Guid("b488bfdc-1cfc-43db-b21b-2b58db2293a3"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6620),
                            Key = "exercises.push-up.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6620),
                            Value = "Push up"
                        },
                        new
                        {
                            Id = new Guid("284039c9-06df-4839-b7d9-b83e69f76542"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6620),
                            Key = "exercises.push-up.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6620),
                            Value = "Klik"
                        },
                        new
                        {
                            Id = new Guid("e5031a4e-cc45-4429-b9a4-1ed358ba3398"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6630),
                            Key = "exercises.push-up.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6630),
                            Value = "PUSHUP"
                        },
                        new
                        {
                            Id = new Guid("1253c3b7-c89b-46ab-9fd4-c4b5c74ed251"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6630),
                            Key = "exercises.push-up.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6630),
                            Value = "KLIK"
                        },
                        new
                        {
                            Id = new Guid("47b71aa7-2419-4778-8c93-a9894805150e"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6630),
                            Key = "exercises.push-up.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6630),
                            Value = "A versatile exercise engaging the chest, shoulders, and triceps. Start in a plank position, lower your body to the ground, and push back up."
                        },
                        new
                        {
                            Id = new Guid("2ea6cd3d-e8f4-4528-9099-201f2e5f34fe"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6640),
                            Key = "exercises.push-up.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6640),
                            Value = "Kliky jsou cvik na posílení horní části těla, zvláště hrudníku, tricepsů a deltových svalů. Provádí se opakováním zvedání a spouštění těla, kdy se opíráte o ruce na zemi a tlačíte se nahoru a dolů."
                        },
                        new
                        {
                            Id = new Guid("925de2bd-1da0-4d49-b3da-19243d38579c"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6640),
                            Key = "exercises.curl.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6640),
                            Value = "Bicep curl"
                        },
                        new
                        {
                            Id = new Guid("fe76252d-c198-4ddf-8292-d6f72416e548"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6640),
                            Key = "exercises.curl.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6640),
                            Value = "Bicepsový zdvih"
                        },
                        new
                        {
                            Id = new Guid("1f56a490-7552-47e0-824a-acd6fcf61234"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6650),
                            Key = "exercises.curl.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6650),
                            Value = "BICEPCURL"
                        },
                        new
                        {
                            Id = new Guid("0283691f-f64a-44f2-bedb-2c63b5a397ef"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6650),
                            Key = "exercises.curl.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6650),
                            Value = "BICEPSOVYZDVIH"
                        },
                        new
                        {
                            Id = new Guid("f8de1c34-0797-4396-9b00-3be2d28bffad"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6650),
                            Key = "exercises.curl.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6650),
                            Value = "An isolation exercise for the biceps. Stand with weights in hand, palms facing forward, and curl the weights towards your shoulders by bending at the elbows."
                        },
                        new
                        {
                            Id = new Guid("d2900632-94ec-4c75-851f-3c77e125b0a3"),
                            CreatedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6660),
                            Key = "exercises.curl.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 11, 13, 1, 51, 411, DateTimeKind.Utc).AddTicks(6660),
                            Value = "Bicepsový zdvih cílí na posílení bicepsů a vykonává se zdvihem váhy směrem k ramenům při ohnutí v loktech."
                        });
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Users.HeightLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Uid");

                    b.ToTable("Heights");
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Users.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Users.WeightLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Uid");

                    b.ToTable("Weights");
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Workouts.ActivityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RepetitionsCount")
                        .HasColumnType("int");

                    b.Property<int>("SetsCount")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<Guid?>("WorkoutEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutEntityId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Workouts.WorkoutEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("VerifiedAtGymId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Workouts.ActivityEntity", b =>
                {
                    b.HasOne("FormUp.Api.Features.v1.Exercises.ExerciseEntity", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormUp.Api.Features.v1.Workouts.WorkoutEntity", null)
                        .WithMany("Activities")
                        .HasForeignKey("WorkoutEntityId");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Workouts.WorkoutEntity", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
