// <auto-generated />
using System;
using FormUp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormUp.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormUp.Api.Features.v1.Exercises.ExerciseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ebc4c6aa-fe13-4a7d-8c8e-c0f1ccc0c70c"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2220),
                            Description = "exercises.squat.description",
                            ImageURL = "https://legionathletics.com/wp-content/uploads/2019/05/arnold-squat.jpg",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2220),
                            Name = "exercises.squat.name",
                            NormalizedName = "exercises.squat.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("2a0e76a3-9fe8-4257-a248-ebb0e939dd0c"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2220),
                            Description = "exercises.dead-lift.description",
                            ImageURL = "https://miro.medium.com/v2/resize:fit:1024/0*UkQCo1eLsXjoXn4v.jpg",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2220),
                            Name = "exercises.dead-lift.name",
                            NormalizedName = "exercises.dead-lift.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("5cb97205-9e18-4fdc-b8d5-489983f60595"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2230),
                            Description = "exercises.shoulder-press.description",
                            ImageURL = "https://legionathletics.com/wp-content/uploads/2023/10/Dumbbell-Shoulder-Press-before-after.png",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2230),
                            Name = "exercises.shoulder-press.name",
                            NormalizedName = "exercises.shoulder-press.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("c0c54c39-69eb-421e-ac62-b418a622647a"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2230),
                            Description = "exercises.pull-up.description",
                            ImageURL = "https://hips.hearstapps.com/hmg-prod/images/mh0418-fit-pul-01-1558551798.jpg?crop=0.749xw:1.00xh;0.251xw,0&resize=1200:*",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2230),
                            Name = "exercises.pull-up.name",
                            NormalizedName = "exercises.pull-up.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("888d4c00-f2cf-410f-8904-809c8ce88d3a"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2230),
                            Description = "exercises.dip.description",
                            ImageURL = "https://www.muscleandfitness.com/wp-content/uploads/2018/07/1109-dip.jpg?w=800&quality=86&strip=all",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2230),
                            Name = "exercises.dip.name",
                            NormalizedName = "exercises.dip.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("33eab256-b60e-4636-9ae8-708b6939ce0c"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2240),
                            Description = "exercises.bench-press.description",
                            ImageURL = "https://caliberstrong.com/wp-content/uploads/2020/04/how-to-bench-press.jpg",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2240),
                            Name = "exercises.bench-press.name",
                            NormalizedName = "exercises.bench-press.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("514321a0-5d0d-4cfb-857f-6b8679fce0fe"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2240),
                            Description = "exercises.lunge.description",
                            ImageURL = "https://hortonbarbell.com/wp-content/uploads/2022/05/Dumbbell-Lunge.png",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2240),
                            Name = "exercises.lunge.name",
                            NormalizedName = "exercises.lunge.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("3c5d332c-696e-4611-a592-cb13bb087401"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2240),
                            Description = "exercises.push-up.description",
                            ImageURL = "https://www.fitnesseducation.edu.au/wp-content/uploads/2017/03/Pushups.jpg",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2240),
                            Name = "exercises.push-up.name",
                            NormalizedName = "exercises.push-up.normalized-name"
                        },
                        new
                        {
                            Id = new Guid("8aa97653-ca11-4875-8e66-517b0f2f63fa"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2250),
                            Description = "exercises.curl.description",
                            ImageURL = "https://hortonbarbell.com/wp-content/uploads/2023/01/How-To-Do-Tempo-Bicep-Curls.png",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2250),
                            Name = "exercises.curl.name",
                            NormalizedName = "exercises.curl.normalized-name"
                        });
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Gyms.GymEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gyms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b97dd29-10f4-4d2b-8849-54102503e434"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2640),
                            Latitude = 49.178859520009325,
                            Longitude = 16.59588166754828,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2640),
                            Name = "Posilovna Velký Průvan"
                        },
                        new
                        {
                            Id = new Guid("ee0b7080-7fdc-48c3-a15c-3a6274daa266"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2650),
                            Latitude = 49.179083949535297,
                            Longitude = 16.596503940037902,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2650),
                            Name = "Posilovna Malý Průvan"
                        },
                        new
                        {
                            Id = new Guid("714924be-bbcd-4bb2-86d8-e3477eab393d"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2650),
                            Latitude = 49.177089060496634,
                            Longitude = 16.606190093594201,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2650),
                            Name = "AZ Fitness"
                        },
                        new
                        {
                            Id = new Guid("bea87b4f-6620-408c-bec7-cbdc677d2fd6"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2650),
                            Latitude = 49.181262112264804,
                            Longitude = 16.60282245697524,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2650),
                            Name = "NewPark Gym"
                        },
                        new
                        {
                            Id = new Guid("a3356ec3-32db-4f24-a71a-a81389f65823"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2660),
                            Latitude = 49.180330210607991,
                            Longitude = 16.606384581697789,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2660),
                            Name = "Energy Fitness Club"
                        },
                        new
                        {
                            Id = new Guid("26179dee-1502-4fe7-a8e3-a724aada497b"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2660),
                            Latitude = 49.215051402565855,
                            Longitude = 16.609402145470618,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2660),
                            Name = "Hulk Gym"
                        },
                        new
                        {
                            Id = new Guid("b87145da-4706-403e-9a49-744300b1a99a"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2660),
                            Latitude = 49.212976899683049,
                            Longitude = 16.609015907373617,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2660),
                            Name = "Fitness Boby"
                        },
                        new
                        {
                            Id = new Guid("5f9c4a54-6d29-4a53-be86-2f4074e4a372"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2670),
                            Latitude = 49.218555432690493,
                            Longitude = 16.624250854578833,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2670),
                            Name = "Blackfield Gym"
                        },
                        new
                        {
                            Id = new Guid("24be6dca-1ab2-4e3e-bb49-8bce3ef60096"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2670),
                            Latitude = 49.190492694739753,
                            Longitude = 16.617386769256324,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2670),
                            Name = "Form Factory Fitness Club Vlněna"
                        },
                        new
                        {
                            Id = new Guid("11921590-5343-4584-9b94-c916c1ec2709"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2670),
                            Latitude = 49.208489226784764,
                            Longitude = 16.605422062883459,
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2670),
                            Name = "Form Factory Fitness Club Lužánky"
                        });
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Translations.TranslationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Locale", "Key");

                    b.ToTable("Translations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("369f8fde-40c1-4afb-91a8-ee64cafdf701"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2370),
                            Key = "exercises.squat.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2370),
                            Value = "Squat"
                        },
                        new
                        {
                            Id = new Guid("0eae7af6-b3e2-47c4-84fa-c2d463945995"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2370),
                            Key = "exercises.squat.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2370),
                            Value = "Dřep"
                        },
                        new
                        {
                            Id = new Guid("201b7530-b784-4d71-a42b-2d92d288ac50"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2380),
                            Key = "exercises.squat.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2380),
                            Value = "SQUAT"
                        },
                        new
                        {
                            Id = new Guid("d067c66d-4b4e-4966-97ee-c3d37752c82f"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2380),
                            Key = "exercises.squat.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2380),
                            Value = "DREP"
                        },
                        new
                        {
                            Id = new Guid("2d958181-3461-498d-9129-5039fc74717b"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2390),
                            Key = "exercises.squat.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2390),
                            Value = "A fundamental lower body exercise targeting the legs, hamstrings, and glutes. Stand with feet shoulder-width apart, lower your body by bending your knees, and return to the starting position."
                        },
                        new
                        {
                            Id = new Guid("2a021daa-4e28-4ddd-8112-a3158e5eb20e"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2390),
                            Key = "exercises.squat.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2390),
                            Value = "Dřep posiluje dolní část těla, především nohy, hamstrings a hýždě. Vykonává se stáním s váhou na ramenou a poklesem do pravého úhlu v kolenou."
                        },
                        new
                        {
                            Id = new Guid("c11973b5-6fc9-4a9b-816d-6a7f969e61bc"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2390),
                            Key = "exercises.dead-lift.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2390),
                            Value = "Dead-lift"
                        },
                        new
                        {
                            Id = new Guid("d8abf6e6-bc1c-4cdf-b39f-7574e4fbaaa1"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2400),
                            Key = "exercises.dead-lift.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2400),
                            Value = "Mrtvý tah"
                        },
                        new
                        {
                            Id = new Guid("08c10cb8-8b3a-4932-85f0-0cb3726f0f52"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2400),
                            Key = "exercises.dead-lift.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2400),
                            Value = "DEADLIFT"
                        },
                        new
                        {
                            Id = new Guid("28b30fc1-5beb-4133-a4c1-6eb1b76619d6"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2400),
                            Key = "exercises.dead-lift.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2400),
                            Value = "MRTVYTAH"
                        },
                        new
                        {
                            Id = new Guid("c6ba98e8-d907-4e67-a56e-57f5a5b92bb0"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2410),
                            Key = "exercises.dead-lift.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2410),
                            Value = "A compound exercise for overall strength, focusing on the back, glutes, hamstrings, and lower back. Start with the weight on the ground, hinge at the hips, lift the weight by straightening your hips and knees."
                        },
                        new
                        {
                            Id = new Guid("c44d3c9c-7871-41d8-aefe-b4ad525822cc"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2410),
                            Key = "exercises.dead-lift.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2410),
                            Value = "Mrtvý tah je cvik na posílení zad, hýždí a hamstringů, provedený ohnutím v pase a zdvihem váhy z podlahy s udržením rovné páteře."
                        },
                        new
                        {
                            Id = new Guid("ae78df6c-9c2a-43e5-92af-bd835d34e392"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2410),
                            Key = "exercises.shoulder-press.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2410),
                            Value = "Shoulder press"
                        },
                        new
                        {
                            Id = new Guid("dd90983d-0f7e-4249-9a2a-a62043b0478b"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2420),
                            Key = "exercises.shoulder-press.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2420),
                            Value = "Tlak na ramena"
                        },
                        new
                        {
                            Id = new Guid("e6289d08-c06b-4d1e-ac0c-35b909feaa1a"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2420),
                            Key = "exercises.shoulder-press.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2420),
                            Value = "SHOULDERPRESS"
                        },
                        new
                        {
                            Id = new Guid("be5f8ad5-9286-4636-a7c2-b7f184520ba4"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2420),
                            Key = "exercises.shoulder-press.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2420),
                            Value = "TLAKNARAMENA"
                        },
                        new
                        {
                            Id = new Guid("bb668781-8f2b-402f-a357-f9984a225c61"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2430),
                            Key = "exercises.shoulder-press.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2430),
                            Value = "An upper body exercise concentrating on shoulder muscles. Whether sitting or standing, press weights or other resistance overhead, emphasizing controlled movements."
                        },
                        new
                        {
                            Id = new Guid("dc26ce0e-557a-4b71-83cc-e05b27bfc2ef"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2430),
                            Key = "exercises.shoulder-press.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2430),
                            Value = "Tlaky na ramena zaměřují se na posílení ramenních svalů a vykonávají se tlačením činek nad hlavu."
                        },
                        new
                        {
                            Id = new Guid("a16a04ea-d22b-4041-a463-92a9ceef8b20"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2430),
                            Key = "exercises.pull-up.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2430),
                            Value = "Pull up"
                        },
                        new
                        {
                            Id = new Guid("fe2bc350-e7a0-41c3-98ac-3413236317ff"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2440),
                            Key = "exercises.pull-up.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2440),
                            Value = "Shyb"
                        },
                        new
                        {
                            Id = new Guid("39b355cc-d43d-4e9d-bd5c-4bb725a961c3"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2440),
                            Key = "exercises.pull-up.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2440),
                            Value = "PULLUP"
                        },
                        new
                        {
                            Id = new Guid("79f3b8e9-2776-4093-812d-9c2ad89acbf2"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2440),
                            Key = "exercises.pull-up.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2440),
                            Value = "SHYB"
                        },
                        new
                        {
                            Id = new Guid("4af29b43-e24a-4e1c-a904-265dcf05d1f7"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2450),
                            Key = "exercises.pull-up.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2450),
                            Value = "An effective upper body exercise primarily targeting the back and biceps. Hang from a bar with palms facing away, pull your body up until your chin passes the bar, and lower back down."
                        },
                        new
                        {
                            Id = new Guid("bce3da81-fe47-4dc4-b04e-4b4309d09165"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2450),
                            Key = "exercises.pull-up.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2450),
                            Value = "Shyb je izolovaný cvik pro tricepsy, provádí se zvedáním váhy pomocí prodloužení paže."
                        },
                        new
                        {
                            Id = new Guid("31e92d13-aa34-460c-8835-427cc10a43d9"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2450),
                            Key = "exercises.dip.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2450),
                            Value = "Dip"
                        },
                        new
                        {
                            Id = new Guid("ab09082e-16c3-4a5b-8546-1390d06f459d"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2460),
                            Key = "exercises.dip.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2460),
                            Value = "Klik na bradlech"
                        },
                        new
                        {
                            Id = new Guid("96647b23-c657-44b0-a4c2-09c9ad98a879"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2460),
                            Key = "exercises.dip.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2460),
                            Value = "DIP"
                        },
                        new
                        {
                            Id = new Guid("9a384f16-736b-485a-9e9c-84f0433b3d8d"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2470),
                            Key = "exercises.dip.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2470),
                            Value = "KLIKNABRADLECH"
                        },
                        new
                        {
                            Id = new Guid("70922f74-f991-4457-a476-7599b30478ce"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2470),
                            Key = "exercises.dip.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2470),
                            Value = "An isolation exercise for the triceps and chest. Support yourself on parallel bars, lower your body by bending your elbows, and push back up."
                        },
                        new
                        {
                            Id = new Guid("6bb28e4b-8e7b-452c-aae9-002063fac5b5"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2470),
                            Key = "exercises.dip.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2470),
                            Value = "Kliky na bradlech posilují horní část těla, zejména hrudník, tricepsy a deltové svaly."
                        },
                        new
                        {
                            Id = new Guid("8e081f4c-9ab2-4e02-b900-504d419ba5b8"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2470),
                            Key = "exercises.bench-press.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2470),
                            Value = "Bench press"
                        },
                        new
                        {
                            Id = new Guid("1e0dfc24-4439-493a-948d-b35a37f3d51b"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2480),
                            Key = "exercises.bench-press.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2480),
                            Value = "Bench press"
                        },
                        new
                        {
                            Id = new Guid("56c31c65-bf72-4e37-a8e7-d9c588ea2579"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2480),
                            Key = "exercises.bench-press.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2480),
                            Value = "BENCHPRESS"
                        },
                        new
                        {
                            Id = new Guid("1ec6665d-590c-4ca1-988c-c8d95bc1aac0"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2490),
                            Key = "exercises.bench-press.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2490),
                            Value = "BENCHPRESS"
                        },
                        new
                        {
                            Id = new Guid("4688fbb1-18d8-47b2-af3b-d919e4060f7d"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2490),
                            Key = "exercises.bench-press.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2490),
                            Value = "A classic chest exercise focusing on the pectoral muscles. Lie on a bench, lower and lift a barbell or dumbbells to and from your chest."
                        },
                        new
                        {
                            Id = new Guid("22d7f88f-ffce-4a94-823b-cfdc0779b6ee"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2490),
                            Key = "exercises.bench-press.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2490),
                            Value = "Bench-press je klasický cvik pro posílení hrudníku, tricepse a delt. "
                        },
                        new
                        {
                            Id = new Guid("c38c015c-2933-40e5-9f62-4a522aa6c6cc"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2490),
                            Key = "exercises.lunge.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2500),
                            Value = "Lunge"
                        },
                        new
                        {
                            Id = new Guid("7803a748-208f-498c-8a46-633b17b7c742"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2500),
                            Key = "exercises.lunge.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2500),
                            Value = "Výpad"
                        },
                        new
                        {
                            Id = new Guid("b05d3652-edc4-4d82-8e9e-500f036e1574"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2500),
                            Key = "exercises.lunge.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2500),
                            Value = "LUNGE"
                        },
                        new
                        {
                            Id = new Guid("4b6332f5-de73-47b0-857c-55d147ee4c44"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2510),
                            Key = "exercises.lunge.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2510),
                            Value = "VYPAD"
                        },
                        new
                        {
                            Id = new Guid("47aacc71-9c5c-4396-8cef-b4e37b4b0c07"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2510),
                            Key = "exercises.lunge.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2510),
                            Value = "A lower body exercise targeting the legs and glutes. Take a step forward with one leg, lower your body until both knees form right angles, then return to the starting position."
                        },
                        new
                        {
                            Id = new Guid("89e64ff6-d0d3-4e13-b177-6e6a441a6531"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2510),
                            Key = "exercises.lunge.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2510),
                            Value = "Výpad je cvik na dolní část těla, střídavým krokem dopředu a poklesem kolena k zemi."
                        },
                        new
                        {
                            Id = new Guid("a3a59ae6-2479-4c97-b78d-70d9ba4b708d"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2520),
                            Key = "exercises.push-up.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2520),
                            Value = "Push up"
                        },
                        new
                        {
                            Id = new Guid("e5711465-7973-4c66-ba58-c0f6159c745d"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2520),
                            Key = "exercises.push-up.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2520),
                            Value = "Klik"
                        },
                        new
                        {
                            Id = new Guid("a8f2b9cb-c9d3-4e49-a204-1986d7e55442"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2520),
                            Key = "exercises.push-up.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2520),
                            Value = "PUSHUP"
                        },
                        new
                        {
                            Id = new Guid("ef50e405-89e6-4343-b1a2-a6e1a298a642"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2530),
                            Key = "exercises.push-up.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2530),
                            Value = "KLIK"
                        },
                        new
                        {
                            Id = new Guid("b718b5fe-e32c-4a19-85d9-e8a2945ce2d5"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2530),
                            Key = "exercises.push-up.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2530),
                            Value = "A versatile exercise engaging the chest, shoulders, and triceps. Start in a plank position, lower your body to the ground, and push back up."
                        },
                        new
                        {
                            Id = new Guid("7d210988-6868-46de-8ebe-83d1c051a144"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2530),
                            Key = "exercises.push-up.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2530),
                            Value = "Kliky jsou cvik na posílení horní části těla, zvláště hrudníku, tricepsů a deltových svalů. Provádí se opakováním zvedání a spouštění těla, kdy se opíráte o ruce na zemi a tlačíte se nahoru a dolů."
                        },
                        new
                        {
                            Id = new Guid("f1895f23-cb15-4439-aa0a-1bf4963464b7"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2540),
                            Key = "exercises.curl.name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2540),
                            Value = "Bicep curl"
                        },
                        new
                        {
                            Id = new Guid("440a2c65-497e-457a-827b-e141e3859acf"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2540),
                            Key = "exercises.curl.name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2540),
                            Value = "Bicepsový zdvih"
                        },
                        new
                        {
                            Id = new Guid("84620e58-4de4-48d3-92d1-01bceb1efe36"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2550),
                            Key = "exercises.curl.normalized-name",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2550),
                            Value = "BICEPCURL"
                        },
                        new
                        {
                            Id = new Guid("1d07f874-1c66-418b-ac4e-43a7a756ead4"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2550),
                            Key = "exercises.curl.normalized-name",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2550),
                            Value = "BICEPSOVYZDVIH"
                        },
                        new
                        {
                            Id = new Guid("9302ba8e-7311-4efe-a22f-5ee11cd2f22f"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2550),
                            Key = "exercises.curl.description",
                            Locale = "en",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2550),
                            Value = "An isolation exercise for the biceps. Stand with weights in hand, palms facing forward, and curl the weights towards your shoulders by bending at the elbows."
                        },
                        new
                        {
                            Id = new Guid("2e8c3810-1f95-4815-aef2-da0c9a94ecd1"),
                            CreatedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2560),
                            Key = "exercises.curl.description",
                            Locale = "cs",
                            ModifiedAt = new DateTime(2024, 1, 12, 17, 42, 12, 780, DateTimeKind.Utc).AddTicks(2560),
                            Value = "Bicepsový zdvih cílí na posílení bicepsů a vykonává se zdvihem váhy směrem k ramenům při ohnutí v loktech."
                        });
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Users.HeightLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Uid");

                    b.ToTable("Heights");
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Users.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Users.WeightLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Uid");

                    b.ToTable("Weights");
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Workouts.ActivityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RepetitionsCount")
                        .HasColumnType("int");

                    b.Property<int>("SetsCount")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Workouts.WorkoutEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("VerifiedAtGymId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Workouts.ActivityEntity", b =>
                {
                    b.HasOne("FormUp.Api.Features.v1.Exercises.ExerciseEntity", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormUp.Api.Features.v1.Workouts.WorkoutEntity", "Workout")
                        .WithMany("Activities")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("FormUp.Api.Features.v1.Workouts.WorkoutEntity", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
