name: Publish
on:
  workflow_dispatch: 
  push:
    branches:
      - master
  
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
          include-prerelease: true
          
      - name: Restore
        run: dotnet restore ./FormUpServer.sln
      
      - name: Build
        run: dotnet build ./FormUpServer.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./FormUpServer.sln --configuration Release --no-build
